//
//  strings.page.swift
//  BtvPlusNew
//
//  Created by JeongCheol Kim on 2021/06/01.
//

import Foundation
extension String{
    struct pageTitle {
        public static let connectBtv = "titleConnectBtv".loaalized()
        public static let connectWifi = "titleConnectWifi".loaalized()
        public static let connectCertificationBtv = "titleConnectCertificationBtv".loaalized()
        public static let connectCertificationUser = "titleConnectCertificationUser".loaalized()
        public static let my = "titleMy".loaalized()
        public static let pairingManagement =  "titlePairingManagement".loaalized()
        public static let pairingGuide = "titlePairingGuide".loaalized()
        public static let myTerminatePurchase =  "titleMyTerminatePurchase".loaalized()
        public static let myOksusu =  "titleMyOksusu".loaalized()
        public static let terminateStb = "titleTerminateStb".loaalized()
        public static let setup = "titleSetup".loaalized()
        public static let purchase = "titlePurchase".loaalized()
        public static let certificationAdult = "titleCertificationAdult".loaalized()
        public static let certificationUser = "titleCertificationUser".loaalized()
     
        public static let privacy = "titlePrivacy".loaalized()
        public static let privacyAndAgree = "titlePrivacyAndAgree".loaalized()
        public static let serviceTerms = "titleServiceTerms".loaalized()
        public static let schedule = "titleSchedule".loaalized()
        public static let modifyProfile = "titleModifyProfile".loaalized()
        public static let watched = "titleWatched".loaalized()
        public static let watchedKids = "titleWatchedKids".loaalized()
        public static let watchHabit = "titleWatchHabit".loaalized()
        public static let bookmarkList = "titleBookmarkList".loaalized()
        public static let purchaseList = "titlePurchaseList".loaalized()
        public static let purchaseTicketList = "titlePurchaseTicketList".loaalized()
        public static let myBenefits = "titleMyBenefits".loaalized()
        public static let myAlram = "titleMyAlram".loaalized()
        public static let recommandFriend = "titleRecommandFriend".loaalized()
        public static let cashCharge = "titleCashCharge".loaalized()
        public static let cashChargeGuide = "titleCashChargeGuide".loaalized()
        
        public static let myRegistCardMember = "titleMyRegistCardMember".loaalized()
        public static let myChangeCardMember = "titleMyChangeCardMember".loaalized()
        public static let myRegistCardOk = "titleMyRegistCardOk".loaalized()
        public static let mobileBtv = "titleMobileBtv".loaalized()
        public static let btv = "titleBtv".loaalized()
        public static let person = "titlePerson".loaalized()
    }
    
    struct pageText {
        public static let pairingText = "pairingText".loaalized()
        public static let pairingText1 = "pairingText1".loaalized()
       
        public static let pairingTitle1 = "pairingTitle1".loaalized()
        public static let pairingTitle2 = "pairingTitle2".loaalized()
        public static let pairingBtnGuide = "pairingBtnGuide".loaalized()
        public static let pairingBtnWifi = "pairingBtnWifi".loaalized()
        public static let pairingBtnWifiSub = "pairingBtnWifiSub".loaalized()
        public static let pairingBtnWifiSubTip = "pairingBtnWifiSubTip".loaalized()
        public static let pairingBtnBtvCertification = "pairingBtnBtvCertification".loaalized()
        public static let pairingBtnBtvCertificationSub = "pairingBtnBtvCertificationSub".loaalized()
        public static let pairingBtnUserCertification = "pairingBtnUserCertification".loaalized()
        public static let pairingBtnUserCertificationSub = "pairingBtnUserCertificationSub".loaalized()
        
        public static let pairingText1Tablet = "pairingText1Tablet".loaalized()
        public static let pairingTitle1Tablet = "pairingTitle1Tablet".loaalized()
        public static let pairingTitle2Tablet = "pairingTitle2Tablet".loaalized()
        public static let pairingBtnWifiSubTablet = "pairingBtnWifiSubTablet".loaalized()
        public static let pairingBtnBtvCertificationSubTablet = "pairingBtnBtvCertificationSubTablet".loaalized()
        public static let pairingBtnUserCertificationSubTablet = "pairingBtnUserCertificationSubTablet".loaalized()
        
        public static let pairingSetupUserText1 = "pairingSetupUserText1".loaalized()
        public static let pairingSetupUserText2 = "pairingSetupUserText2".loaalized()
        public static let pairingSetupUserText2Tablet = "pairingSetupUserText2Tablet".loaalized()
        public static let pairingSetupCharacterSelect = "pairingSetupCharacterSelect".loaalized()
        public static let pairingSetupCharacterSelectSub = "pairingSetupCharacterSelectSub".loaalized()
        public static let pairingSetupUserAgreementAll = "pairingSetupUserAgreementAll".loaalized()
        public static let pairingSetupUserAgreement1 = "pairingSetupUserAgreement1".loaalized()
        public static let pairingSetupUserAgreement2 = "pairingSetupUserAgreement2".loaalized()
        public static let pairingSetupUserAgreement3 = "pairingSetupUserAgreement3".loaalized()
        
        public static let pairingGuideText1Horizontal = "pairingGuideText1Horizontal".loaalized()
        public static let pairingGuideTitle2Horizontal = "pairingGuideTitle2Horizontal".loaalized()
        public static let pairingGuideTip2Horizontal = "pairingGuideTip2Horizontal".loaalized()
        public static let pairingGuideTitle3Horizontal = "pairingGuideTitle3Horizontal".loaalized()
        public static let pairingGuideTitle4Horizontal = "pairingGuideTitle4Horizontal".loaalized()
        
        public static let pairingDeviceText1 = "pairingDeviceText1".loaalized()
        public static let pairingDeviceText2 = "pairingDeviceText2".loaalized()
        public static let pairingDeviceText3 = "pairingDeviceText3".loaalized()
        public static let pairingDeviceText4 = "pairingDeviceText4".loaalized()
        
        public static let pairingBtvText1 = "pairingBtvText1".loaalized()
        public static let pairingBtvText2 = "pairingBtvText2".loaalized()
        public static let pairingBtvText3 = "pairingBtvText3".loaalized()
        public static let pairingBtvText4 = "pairingBtvText4".loaalized()
        public static let pairingBtvText5 = "pairingBtvText5".loaalized()
        
        public static let pairingGuideText1 = "pairingGuideText1".loaalized()
        public static let pairingGuideInfo1 = "pairingGuideInfo1".loaalized()

        public static let pairingGuideTitle2 = "pairingGuideTitle2".loaalized()
        public static let pairingGuideText2 = "pairingGuideText2".loaalized()
        public static let pairingGuideInfo2 = "pairingGuideInfo2".loaalized()
        public static let pairingGuideTip2 = "pairingGuideTip2".loaalized()

        public static let pairingGuideTitle3 = "pairingGuideTitle3".loaalized()
        public static let pairingGuideText3 = "pairingGuideText3".loaalized()
        public static let pairingGuideInfo3 = "pairingGuideInfo3".loaalized()

        public static let pairingGuideTitle4 = "pairingGuideTitle4".loaalized()
        public static let pairingGuideText4 = "pairingGuideText4".loaalized()
        public static let pairingGuideInfo4 = "pairingGuideInfo4".loaalized()
        
        public static let terminateBtvText1 = "terminateBtvText1".loaalized()
        public static let terminateBtvText2 = "terminateBtvText2".loaalized()
        public static let terminateBtvDate = "terminateBtvDate".loaalized()
        
        public static let pairingAppletvText1 = "pairingAppletvText1".loaalized()
        public static let pairingAppletvText2 = "pairingAppletvText2".loaalized()
        
        public static let pairingFamilyInviteText1 = "pairingFamilyInviteText1".loaalized()
        public static let pairingFamilyInviteText2 = "pairingFamilyInviteText2".loaalized()
        public static let pairingFamilyInviteError = "pairingFamilyInviteError".loaalized()
        public static let pairingFamilyInviteErrorHost = "pairingFamilyInviteErrorHost".loaalized()
        public static let pairingFamilyInviteErrorAlreadyPairing = "pairingFamilyInviteErrorAlreadyPairing".loaalized()
        public static let pairingFamilyInviteErrorAnotherPairing = "pairingFamilyInviteErrorAnotherPairing".loaalized()
        public static let pairingFamilyInviteErrorAnotherPairingSub = "pairingFamilyInviteErrorAnotherPairingSub".loaalized()
        public static let pairingFamilyInviteErrorExpired = "pairingFamilyInviteErrorExpired".loaalized()
        public static let pairingFamilyInviteErrorLimited = "pairingFamilyInviteErrorLimited".loaalized()
        public static let pairingFamilyInviteErrorLimitedText = "pairingFamilyInviteErrorLimitedText".loaalized()
        public static let pairingFamilyInviteErrorLimitedSub = "pairingFamilyInviteErrorLimitedSub".loaalized()
        
        public static let setupApp = "setupApp".loaalized()
        public static let setupAppDataAlram = "setupAppDataAlram".loaalized()
        public static let setupAppDataAlramText = "setupAppDataAlramText".loaalized()
        public static let setupAppAutoRemocon = "setupAppAutoRemocon".loaalized()
        public static let setupAppAutoRemoconText = "setupAppAutoRemoconText".loaalized()
        public static let setupAppRemoconVibration = "setupAppRemoconVibration".loaalized()
        public static let setupAppRemoconVibrationText = "setupAppRemoconVibrationText".loaalized()

        public static let setupPlay = "setupPlay".loaalized()
        public static let setupPlayAuto = "setupPlayAuto".loaalized()
        public static let setupPlayAutoText = "setupPlayAutoText".loaalized()
        public static let setupPlayNext = "setupPlayNext".loaalized()
        public static let setupPlayNextText = "setupPlayNextText".loaalized()

        public static let setupAlram = "setupAlram".loaalized()
        public static let setupAlramMarketing = "setupAlramMarketing".loaalized()
        public static let setupAlramMarketingText = "setupAlramMarketingText".loaalized()
        public static let setupAlramMarketingTip1 = "setupAlramMarketingTip1".loaalized()
        public static let setupAlramMarketingTip2 = "setupAlramMarketingTip2".loaalized()
        public static let setupAlramMarketingTip3 = "setupAlramMarketingTip3".loaalized()
        public static let setupAlramMarketingTip4 = "setupAlramMarketingTip4".loaalized()
        public static let setupAlramMarketingTip5 = "setupAlramMarketingTip5".loaalized()

        public static let setupCertification = "setupCertification".loaalized()
        public static let setupCertificationPurchase = "setupCertificationPurchase".loaalized()
        public static let setupCertificationPurchaseText = "setupCertificationPurchaseText".loaalized()
        public static let setupCertificationAge = "setupCertificationAge".loaalized()
        public static let setupCertificationAgeText = "setupCertificationAgeText".loaalized()
        
        public static let setupCertificationKidsExit = "setupCertificationKidsExit".loaalized()
        public static let setupCertificationKidsExitText =  "setupCertificationKidsExitText".loaalized()

        public static let setupChildren = "setupChildren".loaalized()
        public static let setupChildrenHabit = "setupChildrenHabit".loaalized()
        public static let setupChildrenHabitText = "setupChildrenHabitText".loaalized()

        public static let setupHappySenior = "setupHappySenior".loaalized()
        public static let setupHappySeniorPicture = "setupHappySeniorPicture".loaalized()
        public static let setupHappySeniorPictureText = "setupHappySeniorPictureText".loaalized()
        
        public static var setupPossession = "setupPossession".loaalized()
        public static var setupPossessionSet = "setupPossessionSet".loaalized()
        public static var setupPossessionSetText = "setupPossessionSetText".loaalized()
        
        public static var setupOksusu = "setupOksusu".loaalized()
        public static var setupOksusuSet = "setupOksusuSet".loaalized()
        public static var setupOksusuSetText = "setupOksusuSetText".loaalized()
        public static var setupOksusuPurchaseSet = "setupOksusuPurchaseSet".loaalized()
        public static var setupOksusuPurchaseSetText = "setupOksusuPurchaseSetText".loaalized()

        public static let setupGuideNVersion = "setupGuideNVersion".loaalized()
        public static let setupGuide = "setupGuide".loaalized()
        public static let setupVersionLatest = "setupVersionLatest".loaalized()
        public static let setupOpensource = "setupOpensource".loaalized()
        
        public static let myText1 = "myText1".loaalized()
        public static let myText2 = "myText2".loaalized()
        public static let myPairing =  "myPairing".loaalized()
        public static let myPairingInfo = "myPairingInfo".loaalized()
        public static let myConnectedBtv = "myConnectedBtv".loaalized()
        public static let myPairingDate = "myPairingDate".loaalized()
        
        public static let myinviteFammly = "myinviteFammly".loaalized()
        public static let myinviteFammlyText1 = "myinviteFammlyText1".loaalized()
        public static let myinviteFammlyText2 = "myinviteFammlyText2".loaalized()
        public static let myRegistPictureFammly = "myRegistPictureFammly".loaalized()
        public static let myWatchedInfo = "myWatchedInfo".loaalized()
        public static let myWatchedEmpty = "myWatchedEmpty".loaalized()
        public static let myWatchedKids = "myWatchedKids".loaalized()
        public static let myWatchedKidsButton = "myWatchedKidsButton".loaalized()
        public static let myPurchaseEmpty = "myPurchaseEmpty".loaalized()
        public static let myCollectedEmpty = "myCollectedEmpty".loaalized()
        public static let myBookMarkedEmpty =  "myBookMarkedEmpty".loaalized()
        public static let myBookMarkedInfo = "myBookMarkedInfo".loaalized()
        public static let myTicketInfo = "myTicketInfo".loaalized()
        public static let myTicketMore = "myTicketMore".loaalized()
        public static let myAlramInfo = "myAlramInfo".loaalized()
        public static let myAlramEmpty = "myAlramEmpty".loaalized()
        public static let myAlramEmptyPushOn = "myAlramEmptyPushOn".loaalized()
        public static let myAlramEmptyTip = "myAlramEmptyTip".loaalized()
        
        public static let myModifyNickname = "myModifyNickname".loaalized()
        public static let myModifyNicknameText = "myModifyNicknameText".loaalized()
        public static let myModifyNicknameTip = "myModifyNicknameTip".loaalized()
        
        public static let myRegistCardEmptyCardNo = "myRegistCardEmptyCardNo".loaalized()
        public static let myRegistCardEmptyPassword = "myRegistCardEmptyPassword".loaalized()
        public static let myRegistCardEmptyBirth = "myRegistCardEmptyBirth".loaalized()
        public static let myRegistCardBirthPlaceHolder = "myRegistCardBirthPlaceHolder".loaalized()
        public static let myRegistCardPasswordTip = "myRegistCardPasswordTip".loaalized()
        public static let myRegistCardPasswordPlaceHolder = "myRegistCardPasswordPlaceHolder".loaalized()
        
        public static let mySetup = "mySetup".loaalized()
        public static let myRecommandFriend = "myRecommandFriend".loaalized()
        public static let myRecommandFriendReword = "myRecommandFriendReword".loaalized()
        public static let myTerminatePurchaseInfo = "myTerminatePurchaseInfo".loaalized()
        public static let recommandFriendText1 = "recommandFriendText1".loaalized()
        public static let recommandFriendText2 = "recommandFriendText2".loaalized()
        public static let recommandFriendText3 = "recommandFriendText3".loaalized()
        public static let recommandFriendText4 = "recommandFriendText4".loaalized()
        public static let recommandFriendText5 = "recommandFriendText5".loaalized()
        public static let recommandFriendTip = "recommandFriendTip".loaalized()
        public static let recommandFriendTable1 = "recommandFriendTable1".loaalized()
        public static let recommandFriendTable1Sub1 = "recommandFriendTable1Sub1".loaalized()
        public static let recommandFriendTable1Sub2 = "recommandFriendTable1Sub2".loaalized()
        public static let recommandFriendTable1Sub3 = "recommandFriendTable1Sub3".loaalized()

        public static let recommandFriendTable2 = "recommandFriendTable2".loaalized()
        public static let recommandFriendTable2Sub1 = "recommandFriendTable2Sub1".loaalized()
        public static let recommandFriendTable2Sub2 = "recommandFriendTable2Sub2".loaalized()
        public static let recommandFriendTable2Sub3 = "recommandFriendTable2Sub3".loaalized()
        
        
        public static let myBenefitsCoupon = "myBenefitsCoupon".loaalized()
        public static let myBenefitsCouponText = "myBenefitsCouponText".loaalized()
        public static let myBenefitsCouponRegist = "myBenefitsCouponRegist".loaalized()
        public static let myBenefitsCouponEmpty = "myBenefitsCouponEmpty".loaalized()
        public static let myBenefitsCouponInput = "myBenefitsCouponInput".loaalized()
        
        public static let myBenefitsPoint = "myBenefitsPoint".loaalized()
        public static let myBenefitsPointText = "myBenefitsPointText".loaalized()
        public static let myBenefitsPointRegist = "myBenefitsPointRegist".loaalized()
       
        public static let myBenefitsPointEmpty = "myBenefitsPointEmpty".loaalized()
        public static let myBenefitsPointInput = "myBenefitsPointInput".loaalized()
        public static let myBenefitsCash = "myBenefitsCash".loaalized()
        public static let myBenefitsCashText = "myBenefitsCashText".loaalized()
        public static let myBenefitsCashRegist = "myBenefitsCashRegist".loaalized()
        public static let myBenefitsCashEmpty = "myBenefitsCashEmpty".loaalized()
        public static let myBenefitsCashInput = "myBenefitsCashInput".loaalized()
        

        public static let myBenefitsNumberTip = "myBenefitsNumberTip".loaalized()

        public static let myBenefitsDiscount = "myBenefitsDiscount".loaalized()
        public static let myBenefitsDiscountT = "myBenefitsDiscountT".loaalized()
        public static let myBenefitsDiscountOk = "myBenefitsDiscountOk".loaalized()
        public static let myBenefitsDiscountTv = "myBenefitsDiscountTv".loaalized()
        public static let myBenefitsDiscountTvText1 = "myBenefitsDiscountTvText1".loaalized()
        public static let myBenefitsDiscountTvText2 = "myBenefitsDiscountTvText2".loaalized()
        public static let myBenefitsDiscountTInfo1 = "myBenefitsDiscountTInfo1".loaalized()
        public static let myBenefitsDiscountTInfo2 = "myBenefitsDiscountTInfo2".loaalized()
        public static let myBenefitsDiscountOkInfo1 = "myBenefitsDiscountOkInfo1".loaalized()
        public static let myBenefitsDiscountOkInfo2 = "myBenefitsDiscountOkInfo2".loaalized()
        public static let myBenefitsDiscountOkSetup = "myBenefitsDiscountOkSetup".loaalized()
        public static let myBenefitsDiscountOkSetupText = "myBenefitsDiscountOkSetupText".loaalized()
        public static let myBenefitsDiscountOkDelete = "myBenefitsDiscountOkDelete".loaalized()
        public static let myBenefitsDiscountTvInfo1 = "myBenefitsDiscountTvInfo1".loaalized()
        
        public static let myBenefitsRegistOk = "myBenefitsRegistOk".loaalized()
        public static let myBenefitsRegistT = "myBenefitsRegistT".loaalized()
        public static let myBenefitsChangedT = "myBenefitsChangedT".loaalized()
        public static var myBenefitsDiscountOkDeleteConfirm = "myBenefitsDiscountOkDeleteConfirm".loaalized()
        public static var myBenefitsDiscountOkDeleteConfirmText = "myBenefitsDiscountOkDeleteConfirmText".loaalized()
        public static var myBenefitsDiscountTDeleteConfirm = "myBenefitsDiscountTDeleteConfirm".loaalized()
        public static var myBenefitsDiscountTDeleteConfirmText = "myBenefitsDiscountTDeleteConfirmText".loaalized()

        public static let myBenefitsCardEmpty = "myBenefitsCardEmpty".loaalized()
        public static let myBenefitsDiscountTvEmpty = "myBenefitsDiscountTvEmpty".loaalized()
        public static let myBenefitsDiscountTvEmptyTip = "myBenefitsDiscountTvEmptyTip".loaalized()
        
        public static let synopsisDisableNScreen = "synopsisDisableNScreen".loaalized()
        public static let synopsisDisablePurchas = "synopsisDisablePurchas".loaalized()
        public static let synopsisOnlyBtvFree = "synopsisOnlyBtvFree".loaalized()
        public static let synopsisOnlyBtv = "synopsisOnlyBtv".loaalized()
        public static let synopsisWatchOnlyBtv = "synopsisWatchOnlyBtv".loaalized()
        public static let synopsisOnlyPurchasBtv = "synopsisOnlyPurchasBtv".loaalized()
        public static let synopsisTerminationBtv = "synopsisTerminationBtv".loaalized()
        public static let synopsisFreeWatch = "synopsisFreeWatch".loaalized()
        public static let synopsisPossonWatch = "synopsisPossonWatch".loaalized()
        public static let synopsisFreeWatchBtv = "synopsisFreeWatchBtv".loaalized()
        public static let synopsisFreeWatchMonthly = "synopsisFreeWatchMonthly".loaalized()
        public static let synopsisWatchRent = "synopsisWatchRent".loaalized()
        public static let synopsisWatchPeriod = "synopsisWatchPeriod".loaalized()
        public static let synopsisWatchPossn = "synopsisWatchPossn".loaalized()
        public static let synopsisOmnipack = "synopsisOmnipack".loaalized()
        public static let synopsisOmnipackTrailing = "synopsisOmnipackTrailing".loaalized()
        public static let synopsisSummry = "synopsisSummry".loaalized()
        public static let synopsisSiris = "synopsisSiris".loaalized()
        public static let synopsisSirisView = "synopsisSirisView".loaalized()
        public static let synopsisClipView = "synopsisClipView".loaalized()
        public static let synopsisDDay = "synopsisDDay".loaalized()
        public static let synopsisRelationVod = "synopsisRelationVod".loaalized()
        public static let synopsisNoRelationVod = "synopsisNoRelationVod".loaalized()
        public static let synopsisPackageContent = "synopsisPackageContent".loaalized()
        public static let synopsisNoRelationSeries = "synopsisNoRelationSeries".loaalized()
        public static let synopsisNoRelationSeriesMessage = "synopsisNoRelationSeriesMessage".loaalized()
        public static let synopsisNoRelationSeriesMessageHorizontal = "synopsisNoRelationSeriesMessageHorizontal".loaalized()
        public static let synopsisAward = "synopsisAward".loaalized()
        
        
        public static let synopsisCornerPlayNeedPurchased = "synopsisCornerPlayNeedPurchased".loaalized()
        public static let synopsisCornerPlayNotNscreen = "synopsisCornerPlayNotNscreen".loaalized()
        public static let synopsisCornerPlayOnlyPurchasedBtv = "synopsisCornerPlayOnlyPurchasedBtv".loaalized()
        public static let synopsisNextPlay = "synopsisNextPlay".loaalized()
        public static let synopsisNextPlayConfirm = "synopsisNextPlayConfirm".loaalized()
        public static let synopsisNextPlayFail = "synopsisNextPlayFail".loaalized()
        public static let synopsisNextClipPlayConfirm = "synopsisNextClipPlayConfirm".loaalized()
        public static let synopsisNextClipPlayFail = "synopsisNextClipPlayFail".loaalized()
        
        public static let authTitle = "authTitle".loaalized()
        public static let authText = "authText".loaalized()
        public static let authTextMic = "authTextMic".loaalized()
        public static let authTextLocation = "authTextLocation".loaalized()
        
        public static let introTitle1 = "introTitle1".loaalized()
        public static let introText1 = "introText1".loaalized()
        public static let introTitle2 = "introTitle2".loaalized()
        public static let introText2 = "introText2".loaalized()
        public static let introTitle3 = "introTitle3".loaalized()
        public static let introText3 = "introText3".loaalized()
        public static let introTitle4 = "introTitle4".loaalized()
        public static let introText4 = "introText4".loaalized()
        
        public static let introTitleHorizontal1 = "introTitleHorizontal1".loaalized()
        public static let introTextHorizontal1 = "introTextHorizontal1".loaalized()
        public static let introTitleHorizontal2 = "introTitleHorizontal2".loaalized()
        public static let introTextHorizontal2 = "introTextHorizontal2".loaalized()
        public static let introTitleHorizontal3 = "introTitleHorizontal3".loaalized()
        public static let introTextHorizontal3 = "introTextHorizontal3".loaalized()
        public static let introTitleHorizontal4 = "introTitleHorizontal4".loaalized()
        public static let introTextHorizontal4 = "introTextHorizontal4".loaalized()
        
        
        public static let searchLatest = "searchLatest".loaalized()
        public static let searchPopularity = "searchPopularity".loaalized()
        public static let searchResult = "searchResult".loaalized()
        public static let searchEmpty = "searchEmpty".loaalized()
        public static let searchEmptyGuide = "searchEmptyGuide".loaalized()
        public static let searchEmptyTitle = "searchEmptyTitle".loaalized()
        public static let searchDeleteAllConfirm = "searchDeleteAllConfirm".loaalized()
        
        public static let modifyProfileText1 = "modifyProfileText1".loaalized()
        public static let modifyProfileText2 = "modifyProfileText2".loaalized()
        public static let modifyProfileText3 = "modifyProfileText3".loaalized()
        
        public static let adultCertificationText1 = "adultCertificationText1".loaalized()
        public static let adultCertificationText2 = "adultCertificationText2".loaalized()
        public static let adultCertificationText3 = "adultCertificationText3".loaalized()
        
        public static let privacyAndAgreeTitle1 = "privacyAndAgreeTitle1".loaalized()
        public static let privacyAndAgreeTitle2 = "privacyAndAgreeTitle2".loaalized()
        public static let privacyAndAgreeTitle3 = "privacyAndAgreeTitle3".loaalized()
        public static let privacyAndAgreeText1 = "privacyAndAgreeText1".loaalized()
        public static let privacyAndAgreeText2 = "privacyAndAgreeText2".loaalized()
        public static let privacyAndAgreeText3 = "privacyAndAgreeText3".loaalized()
        
        public static let cashChargeGuideText = "cashChargeGuideText".loaalized()
        public static let cashChargeGuideTip = "cashChargeGuideTip".loaalized()
        public static let cashChargeGuideAgree = "cashChargeGuideAgree".loaalized()
        public static let cashChargeGuideButton = "cashChargeGuideButton".loaalized()
        public static let cashChargeGuideAgreeTitle1 = "cashChargeGuideAgreeTitle1".loaalized()
        public static let cashChargeGuideAgreeText1 = "cashChargeGuideAgreeText1".loaalized()
        public static let cashChargeGuideAgreeTitle2 = "cashChargeGuideAgreeTitle2".loaalized()
        public static let cashChargeGuideAgreeText2 = "cashChargeGuideAgreeText2".loaalized()
        public static let cashChargeGuideAgreeTitle3 = "cashChargeGuideAgreeTitle3".loaalized()
        public static let cashChargeGuideAgreeText3 = "cashChargeGuideAgreeText3".loaalized()
        public static let cashChargeGuideAgreeTitle4 = "cashChargeGuideAgreeTitle4".loaalized()
        public static let cashChargeGuideAgreeText4 = "cashChargeGuideAgreeText4".loaalized()
        public static let cashChargeGuideAgreeText = "cashChargeGuideAgreeText".loaalized()

    }
    
}
